# Generated by Django 5.1.2 on 2024-11-04 17:25

import django.db.models.deletion
import django.utils.timezone
import homepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Miniature_Image', models.ImageField(blank=True, null=True, upload_to=homepage.models.Item.uploadDirectoryPath)),
                ('Upload_Date', models.DateField(default=django.utils.timezone.now)),
                ('Alternate_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Language', models.CharField(blank=True, max_length=255, null=True)),
                ('Provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('Current_Collection_Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('Accession_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Tags', models.CharField(blank=True, max_length=255, null=True)),
                ('Bibliography', models.TextField(blank=True, null=True)),
                ('approve_status', models.IntegerField(default=0)),
                ('Media', models.IntegerField()),
                ('Description', models.TextField(blank=True, null=True)),
                ('Author', models.ManyToManyField(related_name='items', to='homepage.author')),
                ('Uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approve_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approval_Date', models.DateField(default=django.utils.timezone.now)),
                ('Approval_Status', models.IntegerField(default=0)),
                ('Approval_File', models.FileField(blank=True, null=True, upload_to='approval_files/')),
                ('Approval_Comment', models.TextField(blank=True, null=True)),
                ('Approval_Admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Approval', to=settings.AUTH_USER_MODEL)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Approval', to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=homepage.models.Item_Image.uploadDirectoryPath, verbose_name='Attachment')),
                ('View_Detail', models.CharField(default='Null', max_length=75)),
                ('Index', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='RTI_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Has_DZI', models.BooleanField(default=False)),
                ('Has_TZI', models.BooleanField(default=False)),
                ('Has_Image', models.BooleanField(default=False)),
                ('Info_File', models.FileField(upload_to='')),
                ('RTI_Zip', models.FileField(default=None, null=True, upload_to=homepage.models.RTI_File.uploadDirectoryPath)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti', to='homepage.item')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('RTI_File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='homepage.rti_file')),
            ],
        ),
    ]
