# Generated by Django 5.1.7 on 2025-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Editable content for the Help Page.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rti_file',
            name='RTI_Zip',
        ),
        migrations.AddField(
            model_name='rti_file',
            name='PTM_File',
            field=models.FileField(blank=True, null=True, upload_to='rti_files/'),
        ),
    ]
