# Generated by Django 5.1.7 on 2025-03-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_helppage_remove_rti_file_rti_zip_rti_file_ptm_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPage',
        ),
    ]
