# Generated by Django 5.2 on 2025-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_helppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rti_file',
            name='Has_DZI',
        ),
        migrations.RemoveField(
            model_name='rti_file',
            name='Has_TZI',
        ),
        migrations.AlterField(
            model_name='rti_file',
            name='Has_Image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rti_file',
            name='PTM_File',
            field=models.FileField(blank=True, null=True, upload_to='ptm_files/'),
        ),
    ]
